version: '3.7'
services:

  rabbitmq:
    restart: always
    image: rabbitmq:3.8
    environment:
      # increase the timeout -- that a worker uses for working an the program and then sending an ack
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit consumer_timeout 86400000
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    deploy:
      mode: global
    networks:
      - crawler-net

  producer:
    restart: always
    image: ghcr.io/anddann/thetis-evaluation:1.0-SNAPSHOT
    depends_on:
      - rabbitmq
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 90s
        window: 240s
    env_file:
      - production.env
    environment:
      - WORKER_NODE=false
      - RABBITMQ_USER=myuser
      - RABBITMQ_PASS=mypassword
    networks:
      - crawler-net

  worker:
    restart: always
    image: ghcr.io/anddann/thetis-evaluation:1.0-SNAPSHOT
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 30s
        window: 120s
    depends_on:
      - rabbitmq
      - producer
    env_file:
      - production.env
    environment:
      - WORKER_NODE=true
      - RABBITMQ_USER=myuser
      - RABBITMQ_PASS=mypassword
      - FILESERVER_HOST=http://fileServer:8000
      - FILESERVER_USER=test
      - FILESERVER_PASS=test
    networks:
      - crawler-net

networks:
  crawler-net:
    external: false